### ISSUE TITLE
Font weight epic

### ISSUE THREAD

**Issue by schne324** [dequelabs/cauldron#855]
## Tasks

In reviewing some UI recently with @bobbyomari, he noticed some issues with our font-weight

- [ ] drop support for [`var(--font-weight-thin)`](https://github.com/dequelabs/cauldron/blob/develop/packages/styles/variables.css#L92) as it is unused (this will be a BREAKING CHANGE)
- [ ] drop support for [`var(--font-weight-light)`](https://github.com/dequelabs/cauldron/blob/develop/packages/styles/variables.css#L93) as it is unused (this will be a BREAKING CHANGE)
  - [ ] no longer need to [import it](https://github.com/dequelabs/cauldron/blob/60782888daab263a83724252e8891c1317da2c89/docs/index.js#L26) either
- [ ] [button's](https://github.com/dequelabs/cauldron/blob/develop/packages/styles/button.css) font-weight should be set to [`var(--font-weight-medium)`](https://github.com/dequelabs/cauldron/blob/develop/packages/styles/variables.css#L95)

**Comment by bobbyomari** [comment]
For clarity, the font-weights are as followed:

- font-weight: 400 = regular
- font-weight: 500 = medium
- font-weight: 700 = bold

Best practices is to use the numerical value and not the words 😄

**Comment by scurker** [comment]
> drop support for [var(--font-weight-thin)](https://github.com/dequelabs/cauldron/blob/develop/packages/styles/variables.css#L92) as it is unused (this will be a BREAKING CHANGE for any cauldron consumers who rely on this var)

It is used in one spot: https://github.com/dequelabs/cauldron/blob/f7af2061c4314f69641af80c9f5bfffee8399f74/packages/styles/forms.css#L224

Am I assuming correctly that we're updating the font weight here with this proposed change?

**Comment by scurker** [comment]
I additionally found other usages of `font-weight-light` as well.

**Comment by scurker** [comment]
We can update the usages of this, but should not remove the variables until we decide we want to release a breaking change.
